# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_view.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Setting(object):
    def setupUi(self, Setting):
        Setting.setObjectName("Setting")
        Setting.resize(321, 343)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Setting)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.group_player_count = QtWidgets.QGroupBox(Setting)
        self.group_player_count.setObjectName("group_player_count")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.group_player_count)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.group_player_count)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spin_player_count = QtWidgets.QSpinBox(self.group_player_count)
        self.spin_player_count.setMinimumSize(QtCore.QSize(0, 30))
        self.spin_player_count.setObjectName("spin_player_count")
        self.horizontalLayout_2.addWidget(self.spin_player_count)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.group_player_count)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spin_computer_count = QtWidgets.QSpinBox(self.group_player_count)
        self.spin_computer_count.setMinimumSize(QtCore.QSize(0, 30))
        self.spin_computer_count.setObjectName("spin_computer_count")
        self.horizontalLayout_3.addWidget(self.spin_computer_count)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.group_player_count)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spin_human_count = QtWidgets.QSpinBox(self.group_player_count)
        self.spin_human_count.setMinimumSize(QtCore.QSize(0, 30))
        self.spin_human_count.setObjectName("spin_human_count")
        self.horizontalLayout_4.addWidget(self.spin_human_count)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.group_player_count)
        self.group_deck_count = QtWidgets.QGroupBox(Setting)
        self.group_deck_count.setObjectName("group_deck_count")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.group_deck_count)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.group_deck_count)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.spin_deck_count = QtWidgets.QSpinBox(self.group_deck_count)
        self.spin_deck_count.setMinimumSize(QtCore.QSize(0, 30))
        self.spin_deck_count.setObjectName("spin_deck_count")
        self.horizontalLayout_5.addWidget(self.spin_deck_count)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        self.verticalLayout_2.addWidget(self.group_deck_count)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_start = QtWidgets.QPushButton(Setting)
        self.btn_start.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_start.setStyleSheet("font-size: 20px;")
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout.addWidget(self.btn_start)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_back = QtWidgets.QPushButton(Setting)
        self.btn_back.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 2)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 6)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.setStretch(2, 3)

        self.retranslateUi(Setting)
        QtCore.QMetaObject.connectSlotsByName(Setting)

    def retranslateUi(self, Setting):
        _translate = QtCore.QCoreApplication.translate
        Setting.setWindowTitle(_translate("Setting", "Form"))
        self.group_player_count.setTitle(_translate("Setting", "Number of Players"))
        self.label_2.setText(_translate("Setting", "Player Count:"))
        self.label_3.setText(_translate("Setting", "Computer:"))
        self.label_4.setText(_translate("Setting", "Human:"))
        self.group_deck_count.setTitle(_translate("Setting", "Number of Decks"))
        self.label.setText(_translate("Setting", "Deck count:"))
        self.btn_start.setText(_translate("Setting", "Play"))
        self.btn_back.setText(_translate("Setting", "Back to Menu"))
